/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icomp.client;

import static icomp.client.AverageClient.getNumbersFromKeyboard;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jp
 */
public class AverageClientGUI extends javax.swing.JFrame {

    private static final String USAGE = "Usage:\n\t $ java -jar AverageClient <serverIP> <serverPort>";
    private static final int N = 10; // amount of numbers for the average
    private int port;
    private double numbers[];
    private AverageClient client;

    /*public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.out.println(USAGE);
            return;
        }
        String serverIP = args[0];
        int port = (int) new Integer(args[1]);

        System.out.println("Digite 10 números:");
        double numbers[] = getNumbersFromKeyboard(N);

        System.out.println("Conectando com o servidor ...");
        AverageClient client = new AverageClient(serverIP, port);

        System.out.println("Requisitando a média ...");
        double avg = client.requestAverage(numbers);
        System.out.println("A média é: " + avg);

        System.out.println("Fechando conexão com o servidor ...");
        client.closeConnection();

    }*/
    /**
     * Creates new form AverageClientGUI
     */
    public AverageClientGUI() {
        initComponents();
        this.numbers = new double[N];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FNum1 = new javax.swing.JTextField();
        FNum2 = new javax.swing.JTextField();
        FNum3 = new javax.swing.JTextField();
        FNum4 = new javax.swing.JTextField();
        FNum5 = new javax.swing.JTextField();
        FNum6 = new javax.swing.JTextField();
        FNum7 = new javax.swing.JTextField();
        FNum8 = new javax.swing.JTextField();
        FNum9 = new javax.swing.JTextField();
        FNum10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente de Médias");

        jLabel1.setText("Digite 10 números");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum1ActionPerformed(evt);
            }
        });

        FNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum2ActionPerformed(evt);
            }
        });

        FNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum3ActionPerformed(evt);
            }
        });

        FNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum4ActionPerformed(evt);
            }
        });

        FNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum5ActionPerformed(evt);
            }
        });

        FNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum6ActionPerformed(evt);
            }
        });

        FNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum7ActionPerformed(evt);
            }
        });

        FNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum8ActionPerformed(evt);
            }
        });

        FNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum9ActionPerformed(evt);
            }
        });

        FNum10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNum10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Média");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(FResult, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNum10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum1ActionPerformed

    private void FNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum2ActionPerformed

    private void FNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum3ActionPerformed

    private void FNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum4ActionPerformed

    private void FNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum5ActionPerformed

    private void FNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum6ActionPerformed

    private void FNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum7ActionPerformed

    private void FNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum8ActionPerformed

    private void FNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum9ActionPerformed

    private void FNum10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNum10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNum10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.sendRequest();
        } catch (IOException ex) {
            Logger.getLogger(AverageClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AverageClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AverageClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AverageClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AverageClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (args.length < 2) {
            System.out.println(USAGE);
            return;
        }
        String serverIP = args[0];
        int port = (int) new Integer(args[1]);
        AverageClient client = new AverageClient(serverIP, port);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AverageClientGUI gui = new AverageClientGUI();
                gui.setVisible(true);
                gui.client = client;
            }
        });
    }

    public void getNumbers() {
        this.numbers[0] = new Double(this.FNum1.getText());
        this.numbers[1] = new Double(this.FNum2.getText());
        this.numbers[2] = new Double(this.FNum3.getText());
        this.numbers[3] = new Double(this.FNum4.getText());
        this.numbers[4] = new Double(this.FNum5.getText());
        this.numbers[5] = new Double(this.FNum6.getText());
        this.numbers[6] = new Double(this.FNum7.getText());
        this.numbers[7] = new Double(this.FNum8.getText());
        this.numbers[8] = new Double(this.FNum9.getText());
        this.numbers[9] = new Double(this.FNum10.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FNum1;
    private javax.swing.JTextField FNum10;
    private javax.swing.JTextField FNum2;
    private javax.swing.JTextField FNum3;
    private javax.swing.JTextField FNum4;
    private javax.swing.JTextField FNum5;
    private javax.swing.JTextField FNum6;
    private javax.swing.JTextField FNum7;
    private javax.swing.JTextField FNum8;
    private javax.swing.JTextField FNum9;
    private javax.swing.JTextField FResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void sendRequest() throws IOException {
        this.getNumbers();
        double avg = this.client.requestAverage(this.numbers);
        this.FResult.setText(avg + "");
        this.jButton1.setEnabled(false);
    }
}
